/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controller.CtrlCheckIn;
import javax.swing.BorderFactory;
import java.awt.Color;

/**
 *
 * @author A Little Shit
 */
public class CheckIn extends javax.swing.JFrame {

    /**
     * Creates new form CheckIn
     */
    private CtrlCheckIn checkin;
    public CheckIn() {
        this.checkin = new CtrlCheckIn(this);
        initComponents();
        this.checkin.add();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        paneInputData = new javax.swing.JPanel();
        lblKamarNomor = new javax.swing.JLabel();
        lblInvoice = new javax.swing.JLabel();
        txtInvoice = new javax.swing.JTextField();
        lblInvoice1 = new javax.swing.JLabel();
        cbNamaTamu = new javax.swing.JComboBox<>();
        lblInvoice2 = new javax.swing.JLabel();
        cbJmlDewasa = new javax.swing.JComboBox<>();
        cbJmlAnak = new javax.swing.JComboBox<>();
        txtTanggalIn = new javax.swing.JTextField();
        lblCheckIn = new javax.swing.JLabel();
        txtWaktuIn = new javax.swing.JTextField();
        txtLamaMenginap = new javax.swing.JTextField();
        lblLamaMenginap = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTanggalOut = new javax.swing.JTextField();
        txtWaktuOut = new javax.swing.JTextField();
        lblCheckOut = new javax.swing.JLabel();
        txtDeposit = new javax.swing.JTextField();
        lblLamaMenginap1 = new javax.swing.JLabel();
        btnBatal = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblJudulTipeKamar = new javax.swing.JLabel();
        lblTipekamar = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblTambahTamu = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lblTambahTamu1 = new javax.swing.JLabel();
        txtBiaya = new javax.swing.JLabel();
        cbNomorKamar = new javax.swing.JComboBox<>();
        checkBiaya = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Check In Hotel");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 123, 32));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Check In");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Input data");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 27, -1, -1));

        paneInputData.setBackground(new java.awt.Color(255, 255, 255));
        paneInputData.setPreferredSize(new java.awt.Dimension(1010, 580));

        lblKamarNomor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblKamarNomor.setText("Kamar Nomor : ");

        lblInvoice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblInvoice.setText("# INVOICE");

        txtInvoice.setText("KODE - #INVOICE");
        txtInvoice.setFocusable(false);

        lblInvoice1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblInvoice1.setText("Nama Tamu");

        cbNamaTamu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih --" }));

        lblInvoice2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblInvoice2.setText("Jumlah Orang");

        cbJmlDewasa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Dewasa --" }));

        cbJmlAnak.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Anak Anak --" }));

        txtTanggalIn.setText("Tanggal Sekarang");
        txtTanggalIn.setFocusable(false);

        lblCheckIn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCheckIn.setText("Check In");

        txtWaktuIn.setText("Waktu Sekarang");
        txtWaktuIn.setFocusable(false);

        txtLamaMenginap.setText("Berapa Hari");
        txtLamaMenginap.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLamaMenginapFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLamaMenginapFocusLost(evt);
            }
        });
        txtLamaMenginap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLamaMenginapKeyTyped(evt);
            }
        });

        lblLamaMenginap.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblLamaMenginap.setText("Lama Menginap");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Hari");

        txtTanggalOut.setEditable(false);
        txtTanggalOut.setText("Tanggal Sekarang + lama");

        txtWaktuOut.setText("Waktu Out hh:mm:ss");
        txtWaktuOut.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtWaktuOutFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtWaktuOutFocusLost(evt);
            }
        });

        lblCheckOut.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCheckOut.setText("Check Out");

        txtDeposit.setText("Deposit");
        txtDeposit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDepositFocusGained(evt);
            }
        });

        lblLamaMenginap1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblLamaMenginap1.setText("Jumlah Deposit (Rp)");

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnSubmit.setText("Check In");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(0, 204, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0), 2));

        lblJudulTipeKamar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblJudulTipeKamar.setForeground(new java.awt.Color(255, 255, 255));
        lblJudulTipeKamar.setText("Tipe Kamar (0) : ");
        lblJudulTipeKamar.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.white)
        );

        lblTipekamar.setForeground(new java.awt.Color(255, 255, 255));
        lblTipekamar.setText("Tidak ada deskripsi");
        lblTipekamar.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblTipekamar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblJudulTipeKamar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJudulTipeKamar, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTipekamar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));

        lblTambahTamu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTambahTamu.setForeground(new java.awt.Color(0, 0, 153));
        lblTambahTamu.setText("Klik disini");
        lblTambahTamu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTambahTamuMouseClicked(evt);
            }
        });

        jLabel9.setText("Jika nama tamu yang dimaksud tidak di temukan untuk ditambah ke Buku tamu");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTambahTamu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTambahTamu)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));

        lblTambahTamu1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTambahTamu1.setText("Total Biaya");
        lblTambahTamu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTambahTamu1MouseClicked(evt);
            }
        });

        txtBiaya.setText("Rp. 0");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTambahTamu1)
                .addGap(29, 29, 29)
                .addComponent(txtBiaya, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBiaya, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lblTambahTamu1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        cbNomorKamar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Nomor --" }));
        cbNomorKamar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbNomorKamarItemStateChanged(evt);
            }
        });

        checkBiaya.setText("Check Biaya");
        checkBiaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBiayaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneInputDataLayout = new javax.swing.GroupLayout(paneInputData);
        paneInputData.setLayout(paneInputDataLayout);
        paneInputDataLayout.setHorizontalGroup(
            paneInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneInputDataLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(paneInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneInputDataLayout.createSequentialGroup()
                        .addGroup(paneInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneInputDataLayout.createSequentialGroup()
                                .addGroup(paneInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblInvoice)
                                    .addComponent(txtInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(paneInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(paneInputDataLayout.createSequentialGroup()
                                        .addComponent(lblInvoice1)
                                        .addGap(0, 183, Short.MAX_VALUE))
                                    .addComponent(cbNamaTamu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(paneInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCheckOut)
                            .addGroup(paneInputDataLayout.createSequentialGroup()
                                .addComponent(txtTanggalOut, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtWaktuOut, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblInvoice2)
                            .addGroup(paneInputDataLayout.createSequentialGroup()
                                .addComponent(cbJmlDewasa, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbJmlAnak, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblCheckIn)
                            .addGroup(paneInputDataLayout.createSequentialGroup()
                                .addComponent(txtTanggalIn, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtWaktuIn, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblLamaMenginap)
                            .addGroup(paneInputDataLayout.createSequentialGroup()
                                .addComponent(txtLamaMenginap, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblLamaMenginap1)
                            .addComponent(txtDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(paneInputDataLayout.createSequentialGroup()
                        .addGroup(paneInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneInputDataLayout.createSequentialGroup()
                                .addComponent(lblKamarNomor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbNomorKamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(paneInputDataLayout.createSequentialGroup()
                                .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(checkBiaya, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        paneInputDataLayout.setVerticalGroup(
            paneInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneInputDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblKamarNomor, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(cbNomorKamar))
                .addGap(18, 18, 18)
                .addGroup(paneInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInvoice)
                    .addComponent(lblInvoice1)
                    .addComponent(lblInvoice2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtInvoice, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(cbNamaTamu)
                    .addComponent(cbJmlDewasa)
                    .addComponent(cbJmlAnak))
                .addGap(18, 18, 18)
                .addGroup(paneInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneInputDataLayout.createSequentialGroup()
                        .addComponent(lblCheckIn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(paneInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTanggalIn, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(txtWaktuIn, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(lblLamaMenginap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(paneInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtLamaMenginap, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCheckOut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(paneInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTanggalOut, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(txtWaktuOut, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(lblLamaMenginap1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDeposit, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addGroup(paneInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkBiaya, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        jPanel1.add(paneInputData, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 67, 1090, 560));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("V1.0");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 640, -1, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("2019, Hotel Indonesia");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 637, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1133, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        this.getCheckin().exit();        
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        this.getCheckin().save();
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void cbNomorKamarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbNomorKamarItemStateChanged
        this.getCheckin().setNomorKamar();
    }//GEN-LAST:event_cbNomorKamarItemStateChanged

    private void lblTambahTamuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTambahTamuMouseClicked
        this.getCheckin().addTamu();
    }//GEN-LAST:event_lblTambahTamuMouseClicked

    private void txtLamaMenginapKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLamaMenginapKeyTyped
        
    }//GEN-LAST:event_txtLamaMenginapKeyTyped

    private void txtLamaMenginapFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLamaMenginapFocusLost
        this.getCheckin().parseCheckOutDate();
    }//GEN-LAST:event_txtLamaMenginapFocusLost

    private void checkBiayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBiayaActionPerformed
        this.getCheckin().checkBiaya();
    }//GEN-LAST:event_checkBiayaActionPerformed

    private void lblTambahTamu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTambahTamu1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTambahTamu1MouseClicked

    private void txtLamaMenginapFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLamaMenginapFocusGained
        txtLamaMenginap.setText("");
    }//GEN-LAST:event_txtLamaMenginapFocusGained

    private void txtDepositFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDepositFocusGained
        txtDeposit.setText("");
    }//GEN-LAST:event_txtDepositFocusGained

    private void txtWaktuOutFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtWaktuOutFocusGained
        txtWaktuOut.setText("00:00:00");
    }//GEN-LAST:event_txtWaktuOutFocusGained

    private void txtWaktuOutFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtWaktuOutFocusLost
//        txtWaktuOut.setText("00:00:00");
    }//GEN-LAST:event_txtWaktuOutFocusLost
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cbJmlAnak;
    private javax.swing.JComboBox<String> cbJmlDewasa;
    private javax.swing.JComboBox<String> cbNamaTamu;
    private javax.swing.JComboBox<String> cbNomorKamar;
    private javax.swing.JButton checkBiaya;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblCheckIn;
    private javax.swing.JLabel lblCheckOut;
    private javax.swing.JLabel lblInvoice;
    private javax.swing.JLabel lblInvoice1;
    private javax.swing.JLabel lblInvoice2;
    private javax.swing.JLabel lblJudulTipeKamar;
    private javax.swing.JLabel lblKamarNomor;
    private javax.swing.JLabel lblLamaMenginap;
    private javax.swing.JLabel lblLamaMenginap1;
    private javax.swing.JLabel lblTambahTamu;
    private javax.swing.JLabel lblTambahTamu1;
    private javax.swing.JLabel lblTipekamar;
    private javax.swing.JPanel paneInputData;
    private javax.swing.JLabel txtBiaya;
    private javax.swing.JTextField txtDeposit;
    private javax.swing.JTextField txtInvoice;
    private javax.swing.JTextField txtLamaMenginap;
    private javax.swing.JTextField txtTanggalIn;
    private javax.swing.JTextField txtTanggalOut;
    private javax.swing.JTextField txtWaktuIn;
    private javax.swing.JTextField txtWaktuOut;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the checkin
     */
    public CtrlCheckIn getCheckin() {
        return checkin;
    }

    /**
     * @return the btnBatal
     */
    public javax.swing.JButton getBtnBatal() {
        return btnBatal;
    }

    /**
     * @return the btnSubmit
     */
    public javax.swing.JButton getBtnSubmit() {
        return btnSubmit;
    }

    /**
     * @return the cbJmlAnak
     */
    public javax.swing.JComboBox<String> getCbJmlAnak() {
        return cbJmlAnak;
    }

    /**
     * @return the cbJmlDewasa
     */
    public javax.swing.JComboBox<String> getCbJmlDewasa() {
        return cbJmlDewasa;
    }

    /**
     * @return the cbNamaTamu
     */
    public javax.swing.JComboBox<String> getCbNamaTamu() {
        return cbNamaTamu;
    }

    /**
     * @return the cbNomorKamar
     */
    public javax.swing.JComboBox<String> getCbNomorKamar() {
        return cbNomorKamar;
    }

    /**
     * @return the jLabel1
     */
    public javax.swing.JLabel getjLabel1() {
        return jLabel1;
    }

    /**
     * @return the jLabel2
     */
    public javax.swing.JLabel getjLabel2() {
        return jLabel2;
    }

    /**
     * @return the jLabel3
     */
    public javax.swing.JLabel getjLabel3() {
        return jLabel3;
    }

    /**
     * @return the jLabel4
     */
    public javax.swing.JLabel getjLabel4() {
        return jLabel4;
    }

    /**
     * @return the jLabel5
     */
    public javax.swing.JLabel getjLabel5() {
        return jLabel5;
    }

    /**
     * @return the jLabel9
     */
    public javax.swing.JLabel getjLabel9() {
        return jLabel9;
    }

    /**
     * @return the jPanel1
     */
    public javax.swing.JPanel getjPanel1() {
        return jPanel1;
    }

    /**
     * @return the jPanel2
     */
    public javax.swing.JPanel getjPanel2() {
        return jPanel2;
    }

    /**
     * @return the jPanel3
     */
    public javax.swing.JPanel getjPanel3() {
        return jPanel3;
    }

    /**
     * @return the jPanel5
     */
    public javax.swing.JPanel getjPanel5() {
        return jPanel5;
    }

    /**
     * @return the lblCheckIn
     */
    public javax.swing.JLabel getLblCheckIn() {
        return lblCheckIn;
    }

    /**
     * @return the lblCheckOut
     */
    public javax.swing.JLabel getLblCheckOut() {
        return lblCheckOut;
    }

    /**
     * @return the lblInvoice
     */
    public javax.swing.JLabel getLblInvoice() {
        return lblInvoice;
    }

    /**
     * @return the lblInvoice1
     */
    public javax.swing.JLabel getLblInvoice1() {
        return lblInvoice1;
    }

    /**
     * @return the lblInvoice2
     */
    public javax.swing.JLabel getLblInvoice2() {
        return lblInvoice2;
    }

    /**
     * @return the lblJudulTipeKamar
     */
    public javax.swing.JLabel getLblJudulTipeKamar() {
        return lblJudulTipeKamar;
    }

    /**
     * @return the lblKamarNomor
     */
    public javax.swing.JLabel getLblKamarNomor() {
        return lblKamarNomor;
    }

    /**
     * @return the lblLamaMenginap
     */
    public javax.swing.JLabel getLblLamaMenginap() {
        return lblLamaMenginap;
    }

    /**
     * @return the lblLamaMenginap1
     */
    public javax.swing.JLabel getLblLamaMenginap1() {
        return lblLamaMenginap1;
    }

    /**
     * @return the lblTambahTamu
     */
    public javax.swing.JLabel getLblTambahTamu() {
        return lblTambahTamu;
    }

    /**
     * @return the lblTipekamar
     */
    public javax.swing.JLabel getLblTipekamar() {
        return lblTipekamar;
    }

    /**
     * @return the paneInputData
     */
    public javax.swing.JPanel getPaneInputData() {
        return paneInputData;
    }

    /**
     * @return the txtDeposit
     */
    public javax.swing.JTextField getTxtDeposit() {
        return txtDeposit;
    }

    /**
     * @return the txtInvoice
     */
    public javax.swing.JTextField getTxtInvoice() {
        return txtInvoice;
    }

    /**
     * @return the txtLamaMenginap
     */
    public javax.swing.JTextField getTxtLamaMenginap() {
        return txtLamaMenginap;
    }

    /**
     * @return the txtTanggalIn
     */
    public javax.swing.JTextField getTxtTanggalIn() {
        return txtTanggalIn;
    }

    /**
     * @return the txtTanggalOut
     */
    public javax.swing.JTextField getTxtTanggalOut() {
        return txtTanggalOut;
    }

    /**
     * @return the txtWaktuIn
     */
    public javax.swing.JTextField getTxtWaktuIn() {
        return txtWaktuIn;
    }

    /**
     * @return the txtWaktuOut
     */
    public javax.swing.JTextField getTxtWaktuOut() {
        return txtWaktuOut;
    }

    /**
     * @return the checkBiaya
     */
    public javax.swing.JButton getCheckBiaya() {
        return checkBiaya;
    }

    /**
     * @return the jPanel6
     */
    public javax.swing.JPanel getjPanel6() {
        return jPanel6;
    }

    /**
     * @return the lblTambahTamu1
     */
    public javax.swing.JLabel getLblTambahTamu1() {
        return lblTambahTamu1;
    }

    /**
     * @return the txtBiaya
     */
    public javax.swing.JLabel getTxtBiaya() {
        return txtBiaya;
    }
}
