/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controller.CtrlCheckOut;
import javax.swing.BorderFactory;
import java.awt.Color;

/**
 *
 * @author A Little Shit
 */
public class CheckOut extends javax.swing.JFrame {

    /**
     * Creates new form CheckIn
     */
    private CtrlCheckOut checkout;
    public CheckOut() {
        this.checkout = new CtrlCheckOut(this);
        initComponents();
        this.checkout.add();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        paneInputData = new javax.swing.JPanel();
        btnBatal = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        lblInvoice3 = new javax.swing.JLabel();
        txtNamaTamu = new javax.swing.JTextField();
        lblInvoice5 = new javax.swing.JLabel();
        cbNomorKamar = new javax.swing.JComboBox<>();
        txtInvoice = new javax.swing.JTextField();
        lblInvoice4 = new javax.swing.JLabel();
        txtDewasa = new javax.swing.JTextField();
        txtTanggalCheckIn = new javax.swing.JTextField();
        lblInvoice6 = new javax.swing.JLabel();
        lblInvoice7 = new javax.swing.JLabel();
        txtWaktuCheckIn = new javax.swing.JTextField();
        txtAnak = new javax.swing.JTextField();
        txtTanggalCheckOut = new javax.swing.JTextField();
        lblInvoice8 = new javax.swing.JLabel();
        txtWaktuCheckOut = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblTipeKamar = new javax.swing.JLabel();
        lblDeskripsiTipeKamar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTagihan = new javax.swing.JTextArea();
        lblTagihan = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Check Out");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 123, 32));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Check Out");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Informasi Check out");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        paneInputData.setBackground(new java.awt.Color(255, 255, 255));
        paneInputData.setPreferredSize(new java.awt.Dimension(1010, 580));

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        lblInvoice3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblInvoice3.setText("Nama Tamu");

        txtNamaTamu.setEnabled(false);

        lblInvoice5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblInvoice5.setText("Pilih Kamar : ");

        cbNomorKamar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Kamar --" }));
        cbNomorKamar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbNomorKamarItemStateChanged(evt);
            }
        });

        txtInvoice.setEnabled(false);

        lblInvoice4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblInvoice4.setText("#INVOICE");

        txtDewasa.setEnabled(false);

        txtTanggalCheckIn.setEnabled(false);

        lblInvoice6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblInvoice6.setText("Waktu Check In");

        lblInvoice7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblInvoice7.setText("Jumlah Tamu");

        txtWaktuCheckIn.setEnabled(false);

        txtAnak.setEnabled(false);

        txtTanggalCheckOut.setEditable(false);
        txtTanggalCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTanggalCheckOutActionPerformed(evt);
            }
        });

        lblInvoice8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblInvoice8.setText("Waktu Check Out");

        txtWaktuCheckOut.setEditable(false);

        jPanel2.setBackground(new java.awt.Color(102, 204, 0));

        lblTipeKamar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTipeKamar.setForeground(new java.awt.Color(255, 255, 255));
        lblTipeKamar.setText("Tipe Kamar (0) :");
        lblTipeKamar.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.white)
        );

        lblDeskripsiTipeKamar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDeskripsiTipeKamar.setForeground(new java.awt.Color(255, 255, 255));
        lblDeskripsiTipeKamar.setText("Tidak ada deskripsi");
        lblDeskripsiTipeKamar.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblTipeKamar, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblDeskripsiTipeKamar, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTipeKamar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDeskripsiTipeKamar, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                .addContainerGap())
        );

        txtTagihan.setColumns(20);
        txtTagihan.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtTagihan.setRows(5);
        jScrollPane1.setViewportView(txtTagihan);

        lblTagihan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTagihan.setText("Rincian Tagihan :");

        javax.swing.GroupLayout paneInputDataLayout = new javax.swing.GroupLayout(paneInputData);
        paneInputData.setLayout(paneInputDataLayout);
        paneInputDataLayout.setHorizontalGroup(
            paneInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneInputDataLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(paneInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneInputDataLayout.createSequentialGroup()
                        .addComponent(lblInvoice5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbNomorKamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(paneInputDataLayout.createSequentialGroup()
                        .addGroup(paneInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, paneInputDataLayout.createSequentialGroup()
                                .addGroup(paneInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(paneInputDataLayout.createSequentialGroup()
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(paneInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(lblInvoice4, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblInvoice3, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtInvoice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                                            .addComponent(txtNamaTamu, javax.swing.GroupLayout.Alignment.LEADING)))
                                    .addComponent(lblTagihan))
                                .addGap(18, 18, 18)
                                .addGroup(paneInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblInvoice7)
                                    .addComponent(lblInvoice8)
                                    .addComponent(lblInvoice6)
                                    .addComponent(txtDewasa, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                    .addComponent(txtTanggalCheckIn)
                                    .addComponent(txtTanggalCheckOut))))
                        .addGroup(paneInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneInputDataLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(paneInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtWaktuCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAnak, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtWaktuCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneInputDataLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(paneInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(74, 74, 74))))))
        );
        paneInputDataLayout.setVerticalGroup(
            paneInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneInputDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbNomorKamar)
                    .addComponent(lblInvoice5, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addGroup(paneInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneInputDataLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblInvoice7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(paneInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneInputDataLayout.createSequentialGroup()
                                .addComponent(txtDewasa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblInvoice6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTanggalCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblInvoice8)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(paneInputDataLayout.createSequentialGroup()
                                .addComponent(txtAnak, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(txtWaktuCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addGroup(paneInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtWaktuCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTanggalCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(61, 61, 61)
                                .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(68, Short.MAX_VALUE))))
                    .addGroup(paneInputDataLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(paneInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneInputDataLayout.createSequentialGroup()
                                .addComponent(lblInvoice4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblInvoice3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNamaTamu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(lblTagihan, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
        );

        jPanel1.add(paneInputData, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 67, 1090, 560));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("V1.0");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 640, -1, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("2019, Hotel Indonesia");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 637, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1133, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        this.getCheckout().exit();
        
    }//GEN-LAST:event_btnBatalActionPerformed

    private void txtTanggalCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTanggalCheckOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTanggalCheckOutActionPerformed

    private void cbNomorKamarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbNomorKamarItemStateChanged
        this.getCheckout().fetchData();
    }//GEN-LAST:event_cbNomorKamarItemStateChanged
    
    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        this.getCheckout().save();
    }//GEN-LAST:event_btnSubmitActionPerformed
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cbNomorKamar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDeskripsiTipeKamar;
    private javax.swing.JLabel lblInvoice3;
    private javax.swing.JLabel lblInvoice4;
    private javax.swing.JLabel lblInvoice5;
    private javax.swing.JLabel lblInvoice6;
    private javax.swing.JLabel lblInvoice7;
    private javax.swing.JLabel lblInvoice8;
    private javax.swing.JLabel lblTagihan;
    private javax.swing.JLabel lblTipeKamar;
    private javax.swing.JPanel paneInputData;
    private javax.swing.JTextField txtAnak;
    private javax.swing.JTextField txtDewasa;
    private javax.swing.JTextField txtInvoice;
    private javax.swing.JTextField txtNamaTamu;
    private javax.swing.JTextArea txtTagihan;
    private javax.swing.JTextField txtTanggalCheckIn;
    private javax.swing.JTextField txtTanggalCheckOut;
    private javax.swing.JTextField txtWaktuCheckIn;
    private javax.swing.JTextField txtWaktuCheckOut;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the checkout
     */
    public CtrlCheckOut getCheckout() {
        return checkout;
    }

    /**
     * @return the btnBatal
     */
    public javax.swing.JButton getBtnBatal() {
        return btnBatal;
    }

    /**
     * @return the btnSubmit
     */
    public javax.swing.JButton getBtnSubmit() {
        return btnSubmit;
    }

    /**
     * @return the cbNomorKamar
     */
    public javax.swing.JComboBox<String> getCbNomorKamar() {
        return cbNomorKamar;
    }

    /**
     * @return the jLabel1
     */
    public javax.swing.JLabel getjLabel1() {
        return jLabel1;
    }

    /**
     * @return the jLabel2
     */
    public javax.swing.JLabel getjLabel2() {
        return jLabel2;
    }

    /**
     * @return the jLabel4
     */
    public javax.swing.JLabel getjLabel4() {
        return jLabel4;
    }

    /**
     * @return the jLabel5
     */
    public javax.swing.JLabel getjLabel5() {
        return jLabel5;
    }

    /**
     * @return the jPanel1
     */
    public javax.swing.JPanel getjPanel1() {
        return jPanel1;
    }

    /**
     * @return the jPanel2
     */
    public javax.swing.JPanel getjPanel2() {
        return jPanel2;
    }

    /**
     * @return the jScrollPane1
     */
    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    /**
     * @return the lblDeskripsiTipeKamar
     */
    public javax.swing.JLabel getLblDeskripsiTipeKamar() {
        return lblDeskripsiTipeKamar;
    }

    /**
     * @return the lblInvoice3
     */
    public javax.swing.JLabel getLblInvoice3() {
        return lblInvoice3;
    }

    /**
     * @return the lblInvoice4
     */
    public javax.swing.JLabel getLblInvoice4() {
        return lblInvoice4;
    }

    /**
     * @return the lblInvoice5
     */
    public javax.swing.JLabel getLblInvoice5() {
        return lblInvoice5;
    }

    /**
     * @return the lblInvoice6
     */
    public javax.swing.JLabel getLblInvoice6() {
        return lblInvoice6;
    }

    /**
     * @return the lblInvoice7
     */
    public javax.swing.JLabel getLblInvoice7() {
        return lblInvoice7;
    }

    /**
     * @return the lblInvoice8
     */
    public javax.swing.JLabel getLblInvoice8() {
        return lblInvoice8;
    }

    /**
     * @return the lblTagihan
     */
    public javax.swing.JLabel getLblTagihan() {
        return lblTagihan;
    }

    /**
     * @return the lblTipeKamar
     */
    public javax.swing.JLabel getLblTipeKamar() {
        return lblTipeKamar;
    }

    /**
     * @return the paneInputData
     */
    public javax.swing.JPanel getPaneInputData() {
        return paneInputData;
    }

    /**
     * @return the txtAnak
     */
    public javax.swing.JTextField getTxtAnak() {
        return txtAnak;
    }

    /**
     * @return the txtDewasa
     */
    public javax.swing.JTextField getTxtDewasa() {
        return txtDewasa;
    }

    /**
     * @return the txtInvoice
     */
    public javax.swing.JTextField getTxtInvoice() {
        return txtInvoice;
    }

    /**
     * @return the txtNamaTamu
     */
    public javax.swing.JTextField getTxtNamaTamu() {
        return txtNamaTamu;
    }

    /**
     * @return the txtTagihan
     */
    public javax.swing.JTextArea getTxtTagihan() {
        return txtTagihan;
    }

    /**
     * @return the txtTanggalCheckIn
     */
    public javax.swing.JTextField getTxtTanggalCheckIn() {
        return txtTanggalCheckIn;
    }

    /**
     * @return the txtTanggalCheckOut
     */
    public javax.swing.JTextField getTxtTanggalCheckOut() {
        return txtTanggalCheckOut;
    }

    /**
     * @return the txtWaktuCheckIn
     */
    public javax.swing.JTextField getTxtWaktuCheckIn() {
        return txtWaktuCheckIn;
    }

    /**
     * @return the txtWaktuCheckOut
     */
    public javax.swing.JTextField getTxtWaktuCheckOut() {
        return txtWaktuCheckOut;
    }
}
