/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controller.CtrlDetailHotel;

/**
 *
 * @author A Little Shit
 */
public class DetailHotel extends javax.swing.JFrame {

    /**
     * Creates new form CheckIn
     */
    private CtrlDetailHotel hotel;
    public DetailHotel() {
        this.hotel = new CtrlDetailHotel(this);
        initComponents();
        this.hotel.add();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        paneInputData = new javax.swing.JPanel();
        lblNomorKamar = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnBatal = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        lblInvoice3 = new javax.swing.JLabel();
        txtNamaHotel = new javax.swing.JTextField();
        txtFax = new javax.swing.JTextField();
        lblInvoice4 = new javax.swing.JLabel();
        txtNomorTelp = new javax.swing.JTextField();
        lblNomorKamar2 = new javax.swing.JLabel();
        lblInvoice5 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblInvoice6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        txtWebsite = new javax.swing.JTextField();
        lblInvoice8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Detail Hotel");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 123, 32));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Detail Hotel");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Informasi hotel");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        paneInputData.setBackground(new java.awt.Color(255, 255, 255));
        paneInputData.setPreferredSize(new java.awt.Dimension(1010, 580));

        lblNomorKamar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNomorKamar.setText("Id Hotel");

        txtId.setText("ID Hotel");
        txtId.setFocusable(false);

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnSubmit.setText("Update");

        lblInvoice3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblInvoice3.setText("Nama Hotel");

        txtNamaHotel.setText("Nama Hotel");
        txtNamaHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaHotelActionPerformed(evt);
            }
        });

        txtFax.setText("Nomor Fax");

        lblInvoice4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblInvoice4.setText("Nomor Fax");

        txtNomorTelp.setText("Nomor Telp");

        lblNomorKamar2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNomorKamar2.setText("Nomor Telepon");

        lblInvoice5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblInvoice5.setText("Alamat");

        txtEmail.setText("Email");

        lblInvoice6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblInvoice6.setText("Email");

        txtAlamat.setEditable(false);
        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        jScrollPane1.setViewportView(txtAlamat);

        txtWebsite.setText("website");

        lblInvoice8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblInvoice8.setText("Website");

        javax.swing.GroupLayout paneInputDataLayout = new javax.swing.GroupLayout(paneInputData);
        paneInputData.setLayout(paneInputDataLayout);
        paneInputDataLayout.setHorizontalGroup(
            paneInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneInputDataLayout.createSequentialGroup()
                .addGroup(paneInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 856, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(paneInputDataLayout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addGroup(paneInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblInvoice5)
                                .addComponent(lblNomorKamar)
                                .addComponent(txtId)
                                .addComponent(txtNamaHotel)
                                .addComponent(lblInvoice3)
                                .addComponent(lblNomorKamar2)
                                .addComponent(txtNomorTelp, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(paneInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(paneInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblInvoice6)
                                    .addComponent(txtEmail)
                                    .addComponent(lblInvoice4)
                                    .addComponent(txtFax, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(paneInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblInvoice8)
                                    .addComponent(txtWebsite, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(paneInputDataLayout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        paneInputDataLayout.setVerticalGroup(
            paneInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneInputDataLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(paneInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(paneInputDataLayout.createSequentialGroup()
                        .addComponent(lblNomorKamar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblInvoice3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNamaHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblNomorKamar2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNomorTelp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneInputDataLayout.createSequentialGroup()
                        .addComponent(lblInvoice4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFax, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblInvoice6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblInvoice8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtWebsite, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(lblInvoice5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(paneInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jPanel1.add(paneInputData, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 67, 1090, 560));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("V1.0");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 640, -1, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("2019, Hotel Indonesia");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 637, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1133, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        this.getHotel().exit();
        
    }//GEN-LAST:event_btnBatalActionPerformed

    private void txtNamaHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaHotelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaHotelActionPerformed
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblInvoice3;
    private javax.swing.JLabel lblInvoice4;
    private javax.swing.JLabel lblInvoice5;
    private javax.swing.JLabel lblInvoice6;
    private javax.swing.JLabel lblInvoice8;
    private javax.swing.JLabel lblNomorKamar;
    private javax.swing.JLabel lblNomorKamar2;
    private javax.swing.JPanel paneInputData;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFax;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNamaHotel;
    private javax.swing.JTextField txtNomorTelp;
    private javax.swing.JTextField txtWebsite;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the hotel
     */
    public CtrlDetailHotel getHotel() {
        return hotel;
    }

    /**
     * @return the btnBatal
     */
    public javax.swing.JButton getBtnBatal() {
        return btnBatal;
    }

    /**
     * @return the btnSubmit
     */
    public javax.swing.JButton getBtnSubmit() {
        return btnSubmit;
    }

    /**
     * @return the jLabel1
     */
    public javax.swing.JLabel getjLabel1() {
        return jLabel1;
    }

    /**
     * @return the jLabel2
     */
    public javax.swing.JLabel getjLabel2() {
        return jLabel2;
    }

    /**
     * @return the jLabel4
     */
    public javax.swing.JLabel getjLabel4() {
        return jLabel4;
    }

    /**
     * @return the jLabel5
     */
    public javax.swing.JLabel getjLabel5() {
        return jLabel5;
    }

    /**
     * @return the jPanel1
     */
    public javax.swing.JPanel getjPanel1() {
        return jPanel1;
    }

    /**
     * @return the jScrollPane1
     */
    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    /**
     * @return the lblInvoice3
     */
    public javax.swing.JLabel getLblInvoice3() {
        return lblInvoice3;
    }

    /**
     * @return the lblInvoice4
     */
    public javax.swing.JLabel getLblInvoice4() {
        return lblInvoice4;
    }

    /**
     * @return the lblInvoice5
     */
    public javax.swing.JLabel getLblInvoice5() {
        return lblInvoice5;
    }

    /**
     * @return the lblInvoice6
     */
    public javax.swing.JLabel getLblInvoice6() {
        return lblInvoice6;
    }

    /**
     * @return the lblInvoice8
     */
    public javax.swing.JLabel getLblInvoice8() {
        return lblInvoice8;
    }

    /**
     * @return the lblNomorKamar
     */
    public javax.swing.JLabel getLblNomorKamar() {
        return lblNomorKamar;
    }

    /**
     * @return the lblNomorKamar2
     */
    public javax.swing.JLabel getLblNomorKamar2() {
        return lblNomorKamar2;
    }

    /**
     * @return the paneInputData
     */
    public javax.swing.JPanel getPaneInputData() {
        return paneInputData;
    }

    /**
     * @return the txtAlamat
     */
    public javax.swing.JTextArea getTxtAlamat() {
        return txtAlamat;
    }

    /**
     * @return the txtEmail
     */
    public javax.swing.JTextField getTxtEmail() {
        return txtEmail;
    }

    /**
     * @return the txtFax
     */
    public javax.swing.JTextField getTxtFax() {
        return txtFax;
    }

    /**
     * @return the txtId
     */
    public javax.swing.JTextField getTxtId() {
        return txtId;
    }

    /**
     * @return the txtNamaHotel
     */
    public javax.swing.JTextField getTxtNamaHotel() {
        return txtNamaHotel;
    }

    /**
     * @return the txtNomorTelp
     */
    public javax.swing.JTextField getTxtNomorTelp() {
        return txtNomorTelp;
    }

    /**
     * @return the txtWebsite
     */
    public javax.swing.JTextField getTxtWebsite() {
        return txtWebsite;
    }
}
