/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import backend.Input;
import backend.Session;
import controller.CtrlHome;
/**
 *
 * @author A Little Shit
 */
public class Main extends javax.swing.JFrame {
    Input input;
    /**
     * @return the Container
     */
    public javax.swing.JPanel getContainer() {
        return Container;
    }

    /**
     * @return the btnBukuTamu
     */
    public javax.swing.JButton getBtnBukuTamu() {
        return btnBukuTamu;
    }

    /**
     * @return the btnInOut
     */
    public javax.swing.JButton getBtnInOut() {
        return btnInOut;
    }

    /**
     * @return the btnKamar
     */
    public javax.swing.JButton getBtnKamar() {
        return btnKamar;
    }

    /**
     * @return the btnKembali
     */
    public javax.swing.JLabel getBtnKembali() {
        return btnKembali;
    }

    /**
     * @return the btnLaporan
     */
    public javax.swing.JButton getBtnLaporan() {
        return btnLaporan;
    }

    /**
     * @return the btnLayanan
     */
    public javax.swing.JButton getBtnLayanan() {
        return btnLayanan;
    }


    /**
     * @return the btnPerusahaan
     */
    public javax.swing.JButton getBtnPerusahaan() {
        return btnPerusahaan;
    }

    /**
     * @return the btnRoomServices
     */
    public javax.swing.JButton getBtnRoomServices() {
        return btnRoomServices;
    }

    /**
     * @return the btnSubMenu0
     */
    public javax.swing.JButton getBtnSubMenu0() {
        return btnSubMenu0;
    }

    /**
     * @return the btnSubMenu1
     */
    public javax.swing.JButton getBtnSubMenu1() {
        return btnSubMenu1;
    }

    /**
     * @return the btnSubMenu2
     */
    public javax.swing.JButton getBtnSubMenu2() {
        return btnSubMenu2;
    }

    /**
     * @return the btnSubMenu3
     */
    public javax.swing.JButton getBtnSubMenu3() {
        return btnSubMenu3;
    }

    /**
     * @return the btnSubMenu4
     */
    public javax.swing.JButton getBtnSubMenu4() {
        return btnSubMenu4;
    }

    /**
     * @return the btnSubMenu5
     */
    public javax.swing.JButton getBtnSubMenu5() {
        return btnSubMenu5;
    }

    /**
     * @return the btnUsersAdmin
     */
    public javax.swing.JButton getBtnUsersAdmin() {
        return btnUsersAdmin;
    }

    /**
     * @return the hotelName
     */
    public javax.swing.JLabel getHotelName() {
        return hotelName;
    }

    /**
     * @return the jLabel1
     */
    public javax.swing.JLabel getjLabel1() {
        return jLabel1;
    }

    /**
     * @return the jLabel2
     */
    public javax.swing.JLabel getjLabel2() {
        return jLabel2;
    }

    /**
     * @return the jLabel6
     */
    public javax.swing.JLabel getjLabel6() {
        return jLabel6;
    }

    /**
     * @return the jLabel7
     */
    public javax.swing.JLabel getjLabel7() {
        return jLabel7;
    }

    /**
     * @return the jPanel3
     */
    public javax.swing.JPanel getjPanel3() {
        return jPanel3;
    }

    /**
     * @return the jPanel4
     */
    public javax.swing.JPanel getjPanel4() {
        return jPanel4;
    }

    /**
     * @return the lblAdmin
     */
    public javax.swing.JLabel getLblAdmin() {
        return lblAdmin;
    }

    /**
     * @return the lblLogOut
     */
    public javax.swing.JLabel getLblLogOut() {
        return lblLogOut;
    }

    /**
     * @return the lblPath
     */
    public javax.swing.JLabel getLblPath() {
        return lblPath;
    }

    /**
     * @return the paneMenu
     */
    public javax.swing.JPanel getPaneMenu() {
        return paneMenu;
    }

    /**
     * @return the paneSubMenu
     */
    public javax.swing.JPanel getPaneSubMenu() {
        return paneSubMenu;
    }
    /**
     * Creates new form Main
     */
    CtrlHome home;
    public Main(Input input){
        this.input = input;
        this.home = new CtrlHome(this);
        initComponents();
        this.home.add(input);
//        paneMenu.setBounds(30, 50, paneWidthDelay, paneMenu.getHeight());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Container = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        hotelName = new javax.swing.JLabel();
        lblLogOut = new javax.swing.JLabel();
        lblPath = new javax.swing.JLabel();
        lblAdmin = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        paneSubMenu = new javax.swing.JPanel();
        btnSubMenu0 = new javax.swing.JButton();
        btnSubMenu1 = new javax.swing.JButton();
        btnSubMenu2 = new javax.swing.JButton();
        btnSubMenu4 = new javax.swing.JButton();
        btnSubMenu3 = new javax.swing.JButton();
        btnSubMenu5 = new javax.swing.JButton();
        btnKembali = new javax.swing.JLabel();
        paneMenu = new javax.swing.JPanel();
        btnInOut = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnKamar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnLayanan = new javax.swing.JButton();
        btnBukuTamu = new javax.swing.JButton();
        btnUsersAdmin = new javax.swing.JButton();
        btnLaporan = new javax.swing.JButton();
        btnPerusahaan = new javax.swing.JButton();
        btnRoomServices = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Main Menu");
        setResizable(false);

        Container.setBackground(new java.awt.Color(255, 255, 255));
        Container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 133, 53));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hotelName.setBackground(new java.awt.Color(0, 168, 33));
        hotelName.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        hotelName.setForeground(new java.awt.Color(255, 255, 255));
        hotelName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hotelName.setText("Hotel Indonesia");
        jPanel3.add(hotelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 250, 90));

        lblLogOut.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblLogOut.setForeground(new java.awt.Color(255, 255, 255));
        lblLogOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogOut.setText("Log Out");
        lblLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogOutMouseClicked(evt);
            }
        });
        jPanel3.add(lblLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 50, 70, 20));

        lblPath.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPath.setForeground(new java.awt.Color(0, 197, 78));
        lblPath.setText("Menu");
        jPanel3.add(lblPath, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 280, 40));

        lblAdmin.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblAdmin.setForeground(new java.awt.Color(255, 255, 255));
        lblAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAdmin.setText("Nama Admin");
        jPanel3.add(lblAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, 170, 30));

        Container.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 90));

        jPanel4.setBackground(new java.awt.Color(0, 87, 34));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        paneSubMenu.setBackground(new java.awt.Color(255, 255, 255));
        paneSubMenu.setPreferredSize(new java.awt.Dimension(1090, 450));

        btnSubMenu0.setBackground(new java.awt.Color(255, 255, 255));
        btnSubMenu0.setText("Null");
        btnSubMenu0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubMenu0ActionPerformed(evt);
            }
        });

        btnSubMenu1.setBackground(new java.awt.Color(255, 255, 255));
        btnSubMenu1.setText("Null");
        btnSubMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubMenu1ActionPerformed(evt);
            }
        });

        btnSubMenu2.setBackground(new java.awt.Color(255, 255, 255));
        btnSubMenu2.setText("Null");
        btnSubMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubMenu2ActionPerformed(evt);
            }
        });

        btnSubMenu4.setBackground(new java.awt.Color(255, 255, 255));
        btnSubMenu4.setText("Null");
        btnSubMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubMenu4ActionPerformed(evt);
            }
        });

        btnSubMenu3.setBackground(new java.awt.Color(255, 255, 255));
        btnSubMenu3.setText("Null");
        btnSubMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubMenu3ActionPerformed(evt);
            }
        });

        btnSubMenu5.setBackground(new java.awt.Color(255, 255, 255));
        btnSubMenu5.setText("Null");
        btnSubMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubMenu5ActionPerformed(evt);
            }
        });

        btnKembali.setText("< Kembali");
        btnKembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKembaliMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout paneSubMenuLayout = new javax.swing.GroupLayout(paneSubMenu);
        paneSubMenu.setLayout(paneSubMenuLayout);
        paneSubMenuLayout.setHorizontalGroup(
            paneSubMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneSubMenuLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(paneSubMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneSubMenuLayout.createSequentialGroup()
                        .addComponent(btnSubMenu4, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSubMenu5, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneSubMenuLayout.createSequentialGroup()
                        .addComponent(btnSubMenu0, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSubMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSubMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSubMenu3, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnKembali))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneSubMenuLayout.setVerticalGroup(
            paneSubMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneSubMenuLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btnKembali)
                .addGap(18, 18, 18)
                .addGroup(paneSubMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubMenu0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubMenu3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paneSubMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubMenu4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubMenu5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(229, Short.MAX_VALUE))
        );

        jPanel4.add(paneSubMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 0, 0, 450));

        paneMenu.setBackground(new java.awt.Color(255, 255, 255));
        paneMenu.setPreferredSize(new java.awt.Dimension(1090, 450));

        btnInOut.setBackground(new java.awt.Color(255, 255, 255));
        btnInOut.setText("Check In/Out");
        btnInOut.setFocusPainted(false);
        btnInOut.setRequestFocusEnabled(false);
        btnInOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInOutActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(177, 177, 177));
        jLabel6.setText("Main Navigation");

        btnKamar.setBackground(new java.awt.Color(255, 255, 255));
        btnKamar.setText("Kamar");
        btnKamar.setRequestFocusEnabled(false);
        btnKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKamarActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(177, 177, 177));
        jLabel7.setText("Hotel Administration");

        btnLayanan.setBackground(new java.awt.Color(255, 255, 255));
        btnLayanan.setText("Layanan");
        btnLayanan.setRequestFocusEnabled(false);
        btnLayanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLayananActionPerformed(evt);
            }
        });

        btnBukuTamu.setBackground(new java.awt.Color(255, 255, 255));
        btnBukuTamu.setText("Buku Tamu");
        btnBukuTamu.setRequestFocusEnabled(false);
        btnBukuTamu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBukuTamuActionPerformed(evt);
            }
        });

        btnUsersAdmin.setBackground(new java.awt.Color(255, 255, 255));
        btnUsersAdmin.setText("Users");
        btnUsersAdmin.setEnabled(false);
        btnUsersAdmin.setRequestFocusEnabled(false);
        btnUsersAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsersAdminActionPerformed(evt);
            }
        });

        btnLaporan.setBackground(new java.awt.Color(255, 255, 255));
        btnLaporan.setText("Laporan");
        btnLaporan.setRequestFocusEnabled(false);
        btnLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporanActionPerformed(evt);
            }
        });

        btnPerusahaan.setBackground(new java.awt.Color(255, 255, 255));
        btnPerusahaan.setText("Hotel");
        btnPerusahaan.setRequestFocusEnabled(false);
        btnPerusahaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerusahaanActionPerformed(evt);
            }
        });

        btnRoomServices.setBackground(new java.awt.Color(255, 255, 255));
        btnRoomServices.setText("Room Services");
        btnRoomServices.setRequestFocusEnabled(false);
        btnRoomServices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoomServicesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneMenuLayout = new javax.swing.GroupLayout(paneMenu);
        paneMenu.setLayout(paneMenuLayout);
        paneMenuLayout.setHorizontalGroup(
            paneMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneMenuLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(paneMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneMenuLayout.createSequentialGroup()
                        .addComponent(btnLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPerusahaan, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneMenuLayout.createSequentialGroup()
                        .addGroup(paneMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, paneMenuLayout.createSequentialGroup()
                                .addComponent(btnKamar, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnLayanan, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBukuTamu, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(btnUsersAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(paneMenuLayout.createSequentialGroup()
                        .addComponent(btnInOut, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRoomServices, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        paneMenuLayout.setVerticalGroup(
            paneMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneMenuLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(paneMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInOut, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRoomServices, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(paneMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKamar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLayanan, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBukuTamu, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUsersAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paneMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPerusahaan, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        jPanel4.add(paneMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 460));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("V1.0");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 480, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("2019, Hotel Indonesia");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        Container.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1090, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Container, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubMenu0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubMenu0ActionPerformed
        this.home.slide0();
    }//GEN-LAST:event_btnSubMenu0ActionPerformed

    private void btnKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKamarActionPerformed
        this.home.slideKamar();
    }//GEN-LAST:event_btnKamarActionPerformed

    private void btnInOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInOutActionPerformed
        this.home.inOut();
        
    }//GEN-LAST:event_btnInOutActionPerformed

    private void btnKembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKembaliMouseClicked
        this.home.back();
        
    }//GEN-LAST:event_btnKembaliMouseClicked

    private void btnRoomServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoomServicesActionPerformed
        this.home.roomServices();
        
    }//GEN-LAST:event_btnRoomServicesActionPerformed

    private void btnLayananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLayananActionPerformed
        this.home.layanan();
    }//GEN-LAST:event_btnLayananActionPerformed

    private void btnBukuTamuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBukuTamuActionPerformed
        this.home.bukuTamu();
    }//GEN-LAST:event_btnBukuTamuActionPerformed

    private void btnUsersAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsersAdminActionPerformed
        this.home.userAdmin();
    }//GEN-LAST:event_btnUsersAdminActionPerformed

    private void btnLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanActionPerformed
        this.home.laporan();
        
    }//GEN-LAST:event_btnLaporanActionPerformed

    private void btnPerusahaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerusahaanActionPerformed
        this.home.perusahaan();
        
        
    }//GEN-LAST:event_btnPerusahaanActionPerformed

    private void btnSubMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubMenu1ActionPerformed
        this.home.slide1();
    }//GEN-LAST:event_btnSubMenu1ActionPerformed

    private void btnSubMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubMenu2ActionPerformed
        this.home.slide2();
    }//GEN-LAST:event_btnSubMenu2ActionPerformed

    private void btnSubMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubMenu4ActionPerformed
        this.home.slide3();
    }//GEN-LAST:event_btnSubMenu4ActionPerformed

    private void btnSubMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubMenu3ActionPerformed
        this.home.slide4();
    }//GEN-LAST:event_btnSubMenu3ActionPerformed

    private void btnSubMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubMenu5ActionPerformed
        this.home.slide5();
    }//GEN-LAST:event_btnSubMenu5ActionPerformed

    private void lblLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogOutMouseClicked
        this.home.logout();
    }//GEN-LAST:event_lblLogOutMouseClicked

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Container;
    private javax.swing.JButton btnBukuTamu;
    private javax.swing.JButton btnInOut;
    private javax.swing.JButton btnKamar;
    private javax.swing.JLabel btnKembali;
    private javax.swing.JButton btnLaporan;
    private javax.swing.JButton btnLayanan;
    private javax.swing.JButton btnPerusahaan;
    private javax.swing.JButton btnRoomServices;
    private javax.swing.JButton btnSubMenu0;
    private javax.swing.JButton btnSubMenu1;
    private javax.swing.JButton btnSubMenu2;
    private javax.swing.JButton btnSubMenu3;
    private javax.swing.JButton btnSubMenu4;
    private javax.swing.JButton btnSubMenu5;
    private javax.swing.JButton btnUsersAdmin;
    private javax.swing.JLabel hotelName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblLogOut;
    private javax.swing.JLabel lblPath;
    private javax.swing.JPanel paneMenu;
    private javax.swing.JPanel paneSubMenu;
    // End of variables declaration//GEN-END:variables
}
