/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import backend.DB;
import backend.Data;
import backend.Hash;
import backend.Input;
import backend.Uuid;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;
import threads.Threads;

/**
 *
 * @author A Little Shit
 */
public class TambahUsers extends javax.swing.JFrame {

    /**
     * Creates new form CheckIn
     */
    public TambahUsers() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        paneInputData = new javax.swing.JPanel();
        lblInvoice2 = new javax.swing.JLabel();
        cbAccessible = new javax.swing.JComboBox<>();
        btnBatal = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        lblInvoice3 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblInvoice5 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        txtPasswordulang = new javax.swing.JPasswordField();
        lblInvoice6 = new javax.swing.JLabel();
        lblInvoice7 = new javax.swing.JLabel();
        lblInvoice8 = new javax.swing.JLabel();
        txtIdPegawai = new javax.swing.JTextField();
        lblInvoice9 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tambah User Admin");

        jPanel1.setBackground(new java.awt.Color(0, 123, 32));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tambah User");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Tambah data User");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        paneInputData.setBackground(new java.awt.Color(255, 255, 255));
        paneInputData.setPreferredSize(new java.awt.Dimension(1010, 580));

        lblInvoice2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblInvoice2.setText("Permission");

        cbAccessible.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih --", "ADMINISTRATOR", "SUPER ADMINISTRATOR" }));

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        lblInvoice3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblInvoice3.setText("Username");

        txtUsername.setText("username");

        lblInvoice5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblInvoice5.setText("Password");

        txtPassword.setText("Password12345678");

        txtPasswordulang.setText("Password12345678");

        lblInvoice6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblInvoice6.setText("Ulangi Password");

        lblInvoice7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblInvoice7.setForeground(new java.awt.Color(255, 0, 0));
        lblInvoice7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblInvoice7.setText("Min. 8 - 16 Karakter");

        lblInvoice8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblInvoice8.setForeground(new java.awt.Color(255, 0, 0));
        lblInvoice8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblInvoice8.setText("Password belum sama");

        txtIdPegawai.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdPegawaiFocusLost(evt);
            }
        });

        lblInvoice9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblInvoice9.setText("Id Pegawai");

        txtEmail.setText("username");

        lblEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEmail.setText("Email");

        javax.swing.GroupLayout paneInputDataLayout = new javax.swing.GroupLayout(paneInputData);
        paneInputData.setLayout(paneInputDataLayout);
        paneInputDataLayout.setHorizontalGroup(
            paneInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneInputDataLayout.createSequentialGroup()
                .addGroup(paneInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneInputDataLayout.createSequentialGroup()
                        .addGap(328, 328, 328)
                        .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneInputDataLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(paneInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(paneInputDataLayout.createSequentialGroup()
                                .addComponent(lblInvoice5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblInvoice7))
                            .addComponent(txtPassword)
                            .addComponent(txtPasswordulang)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneInputDataLayout.createSequentialGroup()
                                .addComponent(lblInvoice6)
                                .addGap(229, 229, 229)
                                .addComponent(lblInvoice8))
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblInvoice3))
                        .addGap(18, 18, 18)
                        .addGroup(paneInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblInvoice9)
                            .addComponent(txtIdPegawai, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                            .addComponent(lblInvoice2)
                            .addComponent(cbAccessible, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEmail)
                            .addComponent(txtEmail))))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        paneInputDataLayout.setVerticalGroup(
            paneInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneInputDataLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(paneInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(paneInputDataLayout.createSequentialGroup()
                        .addComponent(lblInvoice9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIdPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneInputDataLayout.createSequentialGroup()
                        .addComponent(lblInvoice3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(paneInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(paneInputDataLayout.createSequentialGroup()
                        .addGroup(paneInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblInvoice5)
                            .addComponent(lblInvoice7))
                        .addGap(135, 135, 135))
                    .addGroup(paneInputDataLayout.createSequentialGroup()
                        .addGroup(paneInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(paneInputDataLayout.createSequentialGroup()
                                .addComponent(lblEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(paneInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneInputDataLayout.createSequentialGroup()
                                .addGroup(paneInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblInvoice6)
                                    .addComponent(lblInvoice8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPasswordulang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneInputDataLayout.createSequentialGroup()
                                .addComponent(lblInvoice2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbAccessible, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                .addGroup(paneInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        jPanel1.add(paneInputData, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 67, 1090, 560));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("V1.0");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 640, -1, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("2019, Hotel Indonesia");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 637, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1133, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        Threads.get("TambahUsers").exit();
        
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        Input<String> inp = new Input<>();
        inp.set(Uuid.generate());
        inp.set(null);
        inp.set(txtUsername.getText());
        inp.set(txtEmail.getText());
        inp.set(Hash.make(new String(txtPassword.getPassword())));
        inp.set(txtIdPegawai.getText());
        inp.set(cbAccessible.getSelectedItem().toString());
        inp.set("Offline");
        DB.getInstance().exec(Data.tambahUser(inp));

    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtIdPegawaiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdPegawaiFocusLost
        String sql = "SELECT id_pegawai, email, nama_pegawai FROM pegawai WHERE id_pegawai = " + "'" + txtIdPegawai.getText() + "'";
        ResultSet result = DB.getInstance().get(sql);
        try {
            if(result.next())
            {
                txtUsername.setText(result.getString("nama_pegawai").replaceAll("\\s+", ""));
                txtEmail.setText(result.getString("email"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(TambahUsers.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_txtIdPegawaiFocusLost
    
    Timer delay;
    int paneListKamarWidth,paneInputDataWidth,paneX,paneY;
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cbAccessible;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblInvoice2;
    private javax.swing.JLabel lblInvoice3;
    private javax.swing.JLabel lblInvoice5;
    private javax.swing.JLabel lblInvoice6;
    private javax.swing.JLabel lblInvoice7;
    private javax.swing.JLabel lblInvoice8;
    private javax.swing.JLabel lblInvoice9;
    private javax.swing.JPanel paneInputData;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIdPegawai;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtPasswordulang;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
